//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Config
{
    using System;
    using System.Collections.Generic;
    
    
    [System.SerializableAttribute()]
    public class Gun
    {
        
        // id
        public int ID {get;set;}
        // 名称
        public string Name {get;set;}
        // 类型
        public string Type {get;set;}
        // 描述
        public string Desc {get;set;}
        // 攻击力
        public int Act {get;set;}
        // 攻击范围
        public int Range {get;set;}
        // 后坐力
        public int Recoil {get;set;}
    }
}
